# Generated by Django 3.1.2 on 2020-11-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secquiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('soc', 'Типы обществ'), ('tax', 'Налоги'), ('fam', 'Семья'), ('state', 'Государство')], max_length=64, verbose_name='Тема')),
                ('questionText', models.TextField(verbose_name='Вопрос')),
                ('option1', models.CharField(max_length=64, verbose_name='Вариант 1')),
                ('option2', models.CharField(max_length=64, verbose_name='Вариант 2')),
                ('option3', models.CharField(max_length=64, verbose_name='Вариант 3')),
                ('option4', models.CharField(max_length=64, verbose_name='Вариант 4')),
                ('answerText', models.CharField(max_length=64, verbose_name='Правильный вариант')),
            ],
        ),
    ]
