# Generated by Django 3.1.2 on 2020-11-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('soc', 'Типы обществ'), ('tax', 'Налоги'), ('fam', 'Семья'), ('state', 'Государство')], max_length=64, verbose_name='Тема')),
                ('isChosen', models.BooleanField(default=False)),
            ],
        ),
    ]
