# Generated by Django 3.1.2 on 2020-11-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firquiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('soc', 'Типы обществ'), ('tax', 'Налоги'), ('fam', 'Семья'), ('state', 'Государство')], max_length=64, verbose_name='Тема')),
                ('questionText', models.TextField(verbose_name='Вопрос')),
                ('answerText', models.CharField(max_length=64, verbose_name='Правильный вариант')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Тренажер "Вставь слово"',
            },
        ),
        migrations.CreateModel(
            name='Thdquiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('soc', 'Типы обществ'), ('tax', 'Налоги'), ('fam', 'Семья'), ('state', 'Государство')], max_length=64, verbose_name='Тема')),
                ('questionText', models.TextField(verbose_name='Утверждение')),
                ('isTrue', models.BooleanField(default=False, verbose_name='Правильно')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Тренажер "Верю-не верю"',
            },
        ),
        migrations.AlterModelOptions(
            name='secquiz',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Тренажер "Выбери правильный ответ"'},
        ),
        migrations.AlterField(
            model_name='theme',
            name='isChosen',
            field=models.BooleanField(default=False, verbose_name='Выбрана'),
        ),
    ]
