# Generated by Django 3.1.2 on 2020-11-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20201113_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='isChosen',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='theme',
        ),
        migrations.AddField(
            model_name='theme',
            name='isChosen1',
            field=models.BooleanField(default=False, verbose_name='Выбрана'),
        ),
        migrations.AddField(
            model_name='theme',
            name='isChosen2',
            field=models.BooleanField(default=False, verbose_name='Выбрана'),
        ),
        migrations.AddField(
            model_name='theme',
            name='isChosen3',
            field=models.BooleanField(default=False, verbose_name='Выбрана'),
        ),
        migrations.AddField(
            model_name='theme',
            name='isChosen4',
            field=models.BooleanField(default=False, verbose_name='Выбрана'),
        ),
    ]
