# Generated by Django 3.1.2 on 2020-11-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20201116_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thdquiz',
            name='isTrue',
        ),
        migrations.AddField(
            model_name='thdquiz',
            name='answerText',
            field=models.CharField(default='', max_length=64, verbose_name='Правильный вариант'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thdquiz',
            name='option1',
            field=models.CharField(default='', max_length=64, verbose_name='Вариант 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thdquiz',
            name='option2',
            field=models.CharField(default='', max_length=64, verbose_name='Вариант 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theme',
            name='isChosen1',
            field=models.BooleanField(default=False, verbose_name='Выбрана тема "Типы обществ"'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='isChosen2',
            field=models.BooleanField(default=False, verbose_name='Выбрана тема "Налоги"'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='isChosen3',
            field=models.BooleanField(default=False, verbose_name='Выбрана тема "Семья"'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='isChosen4',
            field=models.BooleanField(default=False, verbose_name='Выбрана тема "Государство"'),
        ),
    ]
